manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: zmk-corne
      url-base: https://github.com/KRothfus/zmk-config-nicenano/tree/master
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmkcorne
      remote: zmk-corne
      revision: main
      import: app/west.yml
  self:
    path: config
